### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by JannikKlauke** [timothycrosley/pdocs#16]
Hi everyone,

any chances that the changes in the master branch will be released any time soon? I see google and numpy docstring support has been implemented 3 months ago. Would be nice to have that available in the release version.

Edit:
I just saw that the build failed 3 months ago. Any ideas? @sanzoghenzo @timothycrosley 

Best,

**Comment by JannikKlauke** [comment]
Seems like there is an issue here:

`ModuleNotFoundError: No module named 'dataclasses'`

since dataclasses is missing in the dependencies

**Comment by sanzoghenzo** [comment]
This is because dataclasses were introduced in python 3.7 (my "default" version), and the job is running on 3.6.7.

but that module is only used in a test, so the error can be ignored.

Python 3.6 EOL is in 1 year, should we handle this (checking the python version) or can we solve it by updating the travis ci python version?

**Comment by JannikKlauke** [comment]
You're right the 3.7 build worked. 
See: https://travis-ci.org/github/timothycrosley/pdocs

The OSX one fails too because it doesn't find the hug package. 

I would +1 getting rid of the python 3.6 machine.

**Comment by timothycrosley** [comment]
1.1 has been released :)
